# Dockerfile.agent
FROM python:3.10-slim

WORKDIR /app

# Устанавливаем зависимости для Postgres
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Запускаем скрипт агента
CMD ["python", "agent.py"]